export const storiesDetails = [
    {
      id:1,
      image: "/assets/image/topstoriesimg1.png",
      title: "Lorem ipsum dolor sit amet consectetur.",
      author: "Ashley Chui",
      date: "2 days ago",
      rating: "4.8",
    },
    {
      id:2,
      image: "/assets/image/topstoriesimg2.png",
      title: "Lorem ipsum dolor sit amet consectetur.",
      author: "Ashley Chui",
      date: "2 days ago",
      rating: "4.8",
    },
    {
      id:3,
      image: "/assets/image/topstoriesimg3.png",
      title: "Lorem ipsum dolor sit amet consectetur.",
      author: "Ashley Chui",
      date: "2 days ago",
      rating: "4.8",
    },
    {
      id:4,
      image: "/assets/image/topstoriesimg4.png",
      title: "Lorem ipsum dolor sit amet consectetur.",
      author: "Ashley Chui",
      date: "2 days ago",
      rating: "4.8",
    },
    {
      id:5,
      image: "/assets/image/topstoriesimg5.png",
      title: "Lorem ipsum dolor sit amet consectetur.",
      author: "Ashley Chui",
      date: "2 days ago",
      rating: "4.8",
    },
    {
      id:6,
      image: "/assets/image/topstoriesimg1.png",
      title: "Lorem ipsum dolor sit amet consectetur.",
      author: "Ashley Chui",
      date: "2 days ago",
      rating: "4.8",
    },
    {
      id:7,
      image: "/assets/image/topstoriesimg2.png",
      title: "Lorem ipsum dolor sit amet consectetur.",
      author: "Ashley Chui",
      date: "2 days ago",
      rating: "4.8",
    },
    {
      id:8,
      image: "/assets/image/topstoriesimg3.png",
      title: "Lorem ipsum dolor sit amet consectetur.",
      author: "Ashley Chui",
      date: "2 days ago",
      rating: "4.8",
    },
    
  ];